# Generated by Django 5.2.4 on 2025-09-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='tiktok_link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopee_link',
            field=models.TextField(default=''),
        ),
    ]
