# Generated by Django 5.2.4 on 2025-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_brand_product_tiktok_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_full',
            field=models.TextField(default=''),
        ),
    ]
