# Generated by Django 5.2.4 on 2025-08-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_flashsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashSale',
        ),
    ]
